---
- name: kill
  hosts: localhost

  tasks:
  - name: Terminate every running instance in a region. Use with EXTREME caution.
    amazon.aws.ec2_instance:
      state: absent
      filters:
        instance-state-name: running
        zone: us-east-2
